# Site settings
title: Adam Rae
description: Data Scientist
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dr Adam Rae
user_description: I'm a Data Scientist.
user_title: Data Scientist
email: adam@adamrae.com
twitter_username: raemond
linkedin: adam-rae-8625577
github_username:  raemond
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
